name: 'acr' # Tests against ACR
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        run: docker login -u $ACR_USER -p $ACR_SECRET dcbuilds.azurecr.io
        env:
          ACR_USER: ${{ secrets.ACR_USER }}
          ACR_SECRET: ${{ secrets.ACR_SECRET }}

      - name: Build and run dev container task
        uses: stuartleeks/devcontainer-build-run@v0.1
        env:
          WORLD: World
        with:
          subFolder: acr
          imageName: dcbuilds.azurecr.io/stuartleeks/devcontainer-build-run-examples-acr
          runCmd: echo "$HELLO - $WORLD" && [[ "$HELLO - $WORLD" == "Hello - World" ]]
          env: |
            HELLO=Hello
            WORLD

