name: 'dockerfile-context' # custom Dockerfile and context
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}        

      - name: Build and run dev container task
        uses: stuartleeks/devcontainer-build-run@sl/dockerfile-context # <-- don't do this!
        with:
          subFolder: dockerfile-context
          imageName: ghcr.io/stuartleeks/devcontainer-build-run-examples-dockerfile-context
          runCmd: /tmp/dummy.sh
