name: 'run-args' # dev container with runArgs specified in devcontainer.json
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run dev container task
        uses: stuartleeks/devcontainer-build-run@v0.1
        with:
          subFolder: run-args
          imageName: ghcr.io/stuartleeks/devcontainer-build-run-examples-run-args
          runCmd: echo $HOSTNAME && [[ $HOSTNAME == "my-host" ]]
